---
- hosts: agent
  become: yes
  tasks:
  - name: installing httpd
    package:
     name: httpd
  - name: installing php
    package: 
     name: php
  - name: installing mariadb
    package:
     name: mariadb
   
