---
# tasks file for webserver
- name: installing packages
  package:
   name: "{{item}}"
   state: present
   update_cache: yes
  with_items:
   - httpd
   - php
   - git
  
- name: starting webserver
  service:
   name: "{{item}}"
   state: started
  with_items: 
   - httpd
  
  
